// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

// +build k210

// Package clint provides access to the registers of the CLINT peripheral.
//
// Instances:
//  CLINT  CLINT_BASE  -  -  Core Local Interruptor
// Registers:
//  0x000  32  msip[2]      Hart software interrupt register
//  0x4000 64  mtimecmp[2]  Hart time comparator register
//  0xBFF8 64  mtime        Timer register
// Import:
//  github.com/embeddedgo/kendryte/p/mmap
package clint
