// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

// +build k210

// Package irq provides the list of supported external interrupts.
package irq

const (
	SPI0      = 1
	SPI1      = 2
	SPI_SLAVE = 3
	SPI3      = 4
	I2S0      = 5
	I2S1      = 6
	I2S2      = 7
	I2C0      = 8
	I2C1      = 9
	I2C2      = 10
	UART1     = 11
	UART2     = 12
	UART3     = 13
	TIMER0A   = 14 // TIMER0 channel 0 or 1 interrupt
	TIMER0B   = 15 // TIMER0 channel 2 or 3 interrupt
	TIMER1A   = 16 // TIMER1 channel 0 or 1 interrupt
	TIMER1B   = 17 // TIMER1 channel 2 or 3 interrupt
	TIMER2A   = 18 // TIMER2 channel 0 or 1 interrupt
	TIMER2B   = 19 // TIMER2 channel 2 or 3 interrupt
	RTC       = 20
	WDT0      = 21
	WDT1      = 22
	APB_GPIO  = 23
	DVP       = 24
	KPU       = 25
	FFT       = 26
	DMA0      = 27
	DMA1      = 28
	DMA2      = 29
	DMA3      = 30
	DMA4      = 31
	DMA5      = 32
	UARTHS    = 33
	GPIOHS0   = 34
	GPIOHS1   = 35
	GPIOHS2   = 36
	GPIOHS3   = 37
	GPIOHS4   = 38
	GPIOHS5   = 39
	GPIOHS6   = 40
	GPIOHS7   = 41
	GPIOHS8   = 42
	GPIOHS9   = 43
	GPIOHS10  = 44
	GPIOHS11  = 45
	GPIOHS12  = 46
	GPIOHS13  = 47
	GPIOHS14  = 48
	GPIOHS15  = 49
	GPIOHS16  = 50
	GPIOHS17  = 51
	GPIOHS18  = 52
	GPIOHS19  = 53
	GPIOHS20  = 54
	GPIOHS21  = 55
	GPIOHS22  = 56
	GPIOHS23  = 57
	GPIOHS24  = 58
	GPIOHS25  = 59
	GPIOHS26  = 60
	GPIOHS27  = 61
	GPIOHS28  = 62
	GPIOHS29  = 63
	GPIOHS30  = 64
	GPIOHS31  = 65
)
