// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

// +build k210

// Package mmap provides base memory adresses for all peripherals.
package mmap

// CLINT
const (
	CLINT_BASE uintptr = 0x2000000 // Core Local Interruptor
)

// GPIOHS
const (
	GPIOHS_BASE uintptr = 0x38001000 // High-speed GPIO
)

// PLIC
const (
	PLIC_BASE uintptr = 0xC000000 // Platform-Level Interrupt Controller
)

// UARTHS
const (
	UARTHS_BASE uintptr = 0x38000000 // High-speed UART
)
