// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

// +build k210

// Package uart provides access to the registers of the UART peripheral.
//
// Instances:
//  UART1  UART1_BASE  APB0  UART1  Universal Asynchronous Receiver-Transmitter 1
//  UART2  UART2_BASE  APB0  UART2  Universal Asynchronous Receiver-Transmitter 2
//  UART3  UART3_BASE  APB0  UART3  Universal Asynchronous Receiver-Transmitter 3
// Registers:
//  0x000 32  RBR_DLL_THR    Receive Buffer Register / Divisor Latch (Low) / Transmit Holding Register (depending on context and R/W)
//  0x004 32  DLH_IER        Divisor Latch (High) / Interrupt Enable Register
//  0x008 32  FCR_IIR        FIFO Control Register / Interrupt Identification Register
//  0x00C 32  LCR            Line Control Register
//  0x010 32  MCR            Modem Control Register
//  0x014 32  LSR            Line Status Register
//  0x018 32  MSR            Modem Status Register
//  0x01C 32  SCR            Scratchpad Register
//  0x020 32  LPDLL          Low Power Divisor Latch (Low) Register
//  0x024 32  LPDLH          Low Power Divisor Latch (High) Register
//  0x030 32  SRBR_STHR[16]  Shadow Receive Buffer Register / Shadow Transmit Holding Register (depending on R/W)
//  0x070 32  FAR            FIFO Access Register
//  0x074 32  TFR            Transmit FIFO Read Register
//  0x078 32  RFW            Receive FIFO Write Register
//  0x07C 32  USR            UART Status Register
//  0x080 32  TFL            Transmit FIFO Level
//  0x084 32  RFL            Receive FIFO Level
//  0x088 32  SRR            Software Reset Register
//  0x08C 32  SRTS           Shadow Request to Send Register
//  0x090 32  SBCR           Shadow Break Control Register
//  0x094 32  SDMAM          Shadow DMA Mode
//  0x098 32  SFE            Shadow FIFO Enable
//  0x09C 32  SRT            Shadow RCVR Trigger Register
//  0x0A0 32  STET           Shadow TX Empty Trigger Register
//  0x0A4 32  HTX            Halt TX Regster
//  0x0A8 32  DMASA          DMA Software Acknowledge Register
//  0x0AC 32  TCR            Transfer Control Register
//  0x0B0 32  DE_EN          DE Enable Register
//  0x0B4 32  RE_EN          RE Enable Register
//  0x0B8 32  DET            DE Assertion Time Register
//  0x0BC 32  TAT            Turn-Around Time Register
//  0x0C0 32  DLF            Divisor Latch (Fractional) Register
//  0x0C4 32  RAR            Receive-Mode Address Register
//  0x0C8 32  TAR            Transmit-Mode Address Register
//  0x0CC 32  LCR_EXT        Line Control Register (Extended)
//  0x0F4 32  CPR            Component Parameter Register
//  0x0F8 32  UCV            UART Component Version
//  0x0FC 32  CTR            Component Type Register
// Import:
//  github.com/embeddedgo/kendryte/p/bus
//  github.com/embeddedgo/kendryte/p/mmap
package uart
