// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

// +build k210

// Package irq provides the list of supported external interrupts.
package irq

import "embedded/rtos"

const (
	SPI0      rtos.IRQ = 1
	SPI1      rtos.IRQ = 2
	SPI_SLAVE rtos.IRQ = 3
	SPI3      rtos.IRQ = 4
	I2S0      rtos.IRQ = 5
	I2S1      rtos.IRQ = 6
	I2S2      rtos.IRQ = 7
	I2C0      rtos.IRQ = 8
	I2C1      rtos.IRQ = 9
	I2C2      rtos.IRQ = 10
	UART1     rtos.IRQ = 11
	UART2     rtos.IRQ = 12
	UART3     rtos.IRQ = 13
	TIMER0A   rtos.IRQ = 14 // TIMER0 channel 0 or 1 interrupt
	TIMER0B   rtos.IRQ = 15 // TIMER0 channel 2 or 3 interrupt
	TIMER1A   rtos.IRQ = 16 // TIMER1 channel 0 or 1 interrupt
	TIMER1B   rtos.IRQ = 17 // TIMER1 channel 2 or 3 interrupt
	TIMER2A   rtos.IRQ = 18 // TIMER2 channel 0 or 1 interrupt
	TIMER2B   rtos.IRQ = 19 // TIMER2 channel 2 or 3 interrupt
	RTC       rtos.IRQ = 20
	WDT0      rtos.IRQ = 21
	WDT1      rtos.IRQ = 22
	GPIO      rtos.IRQ = 23
	DVP       rtos.IRQ = 24
	KPU       rtos.IRQ = 25
	FFT       rtos.IRQ = 26
	DMA0      rtos.IRQ = 27
	DMA1      rtos.IRQ = 28
	DMA2      rtos.IRQ = 29
	DMA3      rtos.IRQ = 30
	DMA4      rtos.IRQ = 31
	DMA5      rtos.IRQ = 32
	UARTHS    rtos.IRQ = 33
	GPIOHS0   rtos.IRQ = 34
	GPIOHS1   rtos.IRQ = 35
	GPIOHS2   rtos.IRQ = 36
	GPIOHS3   rtos.IRQ = 37
	GPIOHS4   rtos.IRQ = 38
	GPIOHS5   rtos.IRQ = 39
	GPIOHS6   rtos.IRQ = 40
	GPIOHS7   rtos.IRQ = 41
	GPIOHS8   rtos.IRQ = 42
	GPIOHS9   rtos.IRQ = 43
	GPIOHS10  rtos.IRQ = 44
	GPIOHS11  rtos.IRQ = 45
	GPIOHS12  rtos.IRQ = 46
	GPIOHS13  rtos.IRQ = 47
	GPIOHS14  rtos.IRQ = 48
	GPIOHS15  rtos.IRQ = 49
	GPIOHS16  rtos.IRQ = 50
	GPIOHS17  rtos.IRQ = 51
	GPIOHS18  rtos.IRQ = 52
	GPIOHS19  rtos.IRQ = 53
	GPIOHS20  rtos.IRQ = 54
	GPIOHS21  rtos.IRQ = 55
	GPIOHS22  rtos.IRQ = 56
	GPIOHS23  rtos.IRQ = 57
	GPIOHS24  rtos.IRQ = 58
	GPIOHS25  rtos.IRQ = 59
	GPIOHS26  rtos.IRQ = 60
	GPIOHS27  rtos.IRQ = 61
	GPIOHS28  rtos.IRQ = 62
	GPIOHS29  rtos.IRQ = 63
	GPIOHS30  rtos.IRQ = 64
	GPIOHS31  rtos.IRQ = 65
)
