// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

// +build k210

// Package timer provides access to the registers of the TIMER0 peripheral.
//
// Instances:
//  TIMER0  TIMER0_BASE  APB0  TIMER0A,TIMER0B  Timer 0
//  TIMER1  TIMER1_BASE  APB0  TIMER1A,TIMER1B  Timer 1
//  TIMER2  TIMER2_BASE  APB0  TIMER2A,TIMER2B  Timer 2
// Registers:
//  0x000 32  CH{LOAD,CURRENT,CONTROL,EOI,INTSTAT}[4]  Load Count Register; Current Value Register; Control Register; Interrupt Clear Register; Interrupt Status Register
//  0x0A0 32  INTSTAT_ALL                              Interrupt Status Register
//  0x0A4 32  EOI_ALL                                  Interrupt Clear Register
//  0x0A8 32  RAW_INTSTAT_ALL                          Raw Interrupt Status Register
//  0x0AC 32  COMP_VERSION                             Component Version Register
//  0x0B0 32  LOAD_COUNT2[4]                           Load Count2 Register
// Import:
//  github.com/embeddedgo/kendryte/p/bus
//  github.com/embeddedgo/kendryte/p/mmap
package timer

const (
	ENABLE     CONTROL = 0x01 << 0 //+ ENABLE
	MODE       CONTROL = 0x01 << 1 //+ MODE
	FREE       CONTROL = 0x00 << 1 //  FREE_MODE
	USER       CONTROL = 0x01 << 1 //  USER_MODE
	INTERRUPT  CONTROL = 0x01 << 2 //+ INTERRUPT_MASK
	PWM_ENABLE CONTROL = 0x01 << 3 //+ PWM_ENABLE
)

const (
	ENABLEn     = 0
	MODEn       = 1
	INTERRUPTn  = 2
	PWM_ENABLEn = 3
)
