// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

// +build k210

// Package plic provides access to the registers of the PLIC peripheral.
//
// Instances:
//  PLIC  PLIC_BASE  -  -  Platform-Level Interrupt Controller
// Registers:
//  0x000  32  priority[1024]  Interrupt Source Priority Register
//  0x1000 32  pending[32]     Interrupt Pending Register
// Import:
//  github.com/embeddedgo/kendryte/p/mmap
package plic
