// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

// +build k210

// Package uarths provides access to the registers of the UARTHS peripheral.
//
// Instances:
//  UARTHS  UARTHS_BASE  -  UARTHS  High-speed UART
// Registers:
//  0x000 32  txdata  Transmit Data Register
//  0x004 32  rxdata  Receive Data Register
//  0x008 32  txctrl  Transmit Control Register
//  0x00C 32  rxctrl  Receive Control Register
//  0x010 32  ie      Interrupt Enable Register
//  0x014 32  ip      Interrupt Pending Register
//  0x018 32  div     Baud Rate Divisor Register
// Import:
//  github.com/embeddedgo/kendryte/p/mmap
package uarths

const (
	data txdata = 0x00 << 0 //+ Transmit data
	full txdata = 0x00 << 0 //+ Transmit FIFO full
)

const (
	datan = 0
	fulln = 0
)

const (
	data  rxdata = 0x00 << 0 //+ Received data
	empty rxdata = 0x00 << 0 //+ Receive FIFO empty
)

const (
	datan  = 0
	emptyn = 0
)

const (
	txen  txctrl = 0x00 << 0 //+ Transmit enable
	nstop txctrl = 0x00 << 0 //+ Number of stop bits
	txcnt txctrl = 0x00 << 0 //+ Transmit watermark level
)

const (
	txenn  = 0
	nstopn = 0
	txcntn = 0
)

const (
	rxen  rxctrl = 0x00 << 0 //+ Receive enable
	rxcnt rxctrl = 0x00 << 0 //+ Receive watermark level
)

const (
	rxenn  = 0
	rxcntn = 0
)

const (
	txwm ie = 0x00 << 0 //+ Transmit watermark interrupt enable
	rxwm ie = 0x00 << 0 //+ Receive watermark interrupt enable
)

const (
	txwmn = 0
	rxwmn = 0
)

const (
	txwm ip = 0x00 << 0 //+ Transmit watermark interrupt pending
	rxwm ip = 0x00 << 0 //+ Receive watermark interrupt pending
)

const (
	txwmn = 0
	rxwmn = 0
)

const (
	div div = 0x00 << 0 //+ Baud rate divisor
)

const (
	divn = 0
)
