// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

// +build k210

// Package uarths provides access to the registers of the UARTHS peripheral.
//
// Instances:
//  UARTHS  UARTHS_BASE  -  UARTHS  High-speed UART
// Registers:
//  0x000 32  TXDATA  Transmit Data Register
//  0x004 32  RXDATA  Receive Data Register
//  0x008 32  TXCTRL  Transmit Control Register
//  0x00C 32  RXCTRL  Receive Control Register
//  0x010 32  IE      Interrupt Enable Register
//  0x014 32  IP      Interrupt Pending Register
//  0x018 32  DIV     Baud Rate Divisor Register
// Import:
//  github.com/embeddedgo/kendryte/p/mmap
package uarths

const (
	TXD    TXDATA = 0xFF << 0  //+ Transmit data
	TXFULL TXDATA = 0x01 << 31 //+ Transmit FIFO full
)

const (
	TXDn    = 0
	TXFULLn = 31
)

const (
	RXD     RXDATA = 0xFF << 0  //+ Received data
	RXEMPTY RXDATA = 0x01 << 31 //+ Receive FIFO empty
)

const (
	RXDn     = 0
	RXEMPTYn = 31
)

const (
	TXEN  TXCTRL = 0x01 << 0  //+ Transmit enable
	NSTOP TXCTRL = 0x01 << 1  //+ Number of stop bits
	TXCNT TXCTRL = 0x07 << 16 //+ Transmit watermark level
)

const (
	TXENn  = 0
	NSTOPn = 1
	TXCNTn = 16
)

const (
	RXEN  RXCTRL = 0x01 << 0  //+ Receive enable
	RXCNT RXCTRL = 0x07 << 16 //+ Receive watermark level
)

const (
	RXENn  = 0
	RXCNTn = 16
)

const (
	TXWMIE IE = 0x01 << 0 //+ Transmit watermark interrupt enable
	RXWMIE IE = 0x01 << 1 //+ Receive watermark interrupt enable
)

const (
	TXWMIEn = 0
	RXWMIEn = 1
)

const (
	TXWMIP IP = 0x01 << 0 //+ Transmit watermark interrupt pending
	RXWMIP IP = 0x01 << 1 //+ Receive watermark interrupt pending
)

const (
	TXWMIPn = 0
	RXWMIPn = 1
)
